LOCAL_PATH := $(call my-dir)


include $(CLEAR_VARS)
LOCAL_CERTIFICATE := shared
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := OpenCamera
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_OWNER := MarkHarman
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_TAGS := optional
LOCAL_PRIVILEGED_MODULE := true
LOCAL_SRC_FILES := OpenCamera.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_CERTIFICATE := shared
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := RetroMusicPlayer
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_OWNER := MonkeyCodeApps
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := retromusicplayer.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := SysLog
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := SysLog.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := SoundPickerPrebuilt
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := SoundPickerPrebuilt.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := LiveBoot
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_PRIVILEGED_MODULE := true
LOCAL_SRC_FILES := LiveBoot.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := Fleksy
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Fleksy.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := EvolveSMS
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := EvolveSMS.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := MagiskManager
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := MagiskManager.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_BUILT_MODULE_STEM := package.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE := Substratum
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Substratum.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := NovaLauncher
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_SRC_FILES := NovaLauncher_6.0-beta5.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := BetterBatteryStats
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_PRIVILEGED_MODULE := true
LOCAL_SRC_FILES := BetterBatteryStats.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_BUILT_MODULE_STEM := package.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := SolidExplorer
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := SolidExplorer.apk
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_BUILT_MODULE_STEM := package.apk
LOCAL_CERTIFICATE := platform
LOCAL_DEX_PREOPT := false
LOCAL_MODULE := TrebleApp
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_PRIVILEGED_MODULE := true
LOCAL_SRC_FILES := TrebleApp.apk
include $(BUILD_PREBUILT)



# include $(CLEAR_VARS)
# LOCAL_CERTIFICATE := PRESIGNED
# LOCAL_DEX_PREOPT := false
# LOCAL_MODULE := WallpaperPickerPre
# LOCAL_MODULE_CLASS := APPS
# LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
# LOCAL_MODULE_TAGS := optional
# LOCAL_PRIVILEGED_MODULE := true
# LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
# include $(BUILD_PREBUILT)

# include $(CLEAR_VARS)
# LOCAL_MODULE := CalculatorPre
# LOCAL_MODULE_OWNER := Google
# LOCAL_SRC_FILES := CalculatorPre.apk
# LOCAL_CERTIFICATE := shared
# LOCAL_MODULE_TAGS := optional
# LOCAL_MODULE_CLASS := APPS
# LOCAL_MODULE_SUFFIX := .apk
# LOCAL_PRIVILEGED_MODULE := true
# LOCAL_DEX_PREOPT := false
# include $(BUILD_PREBUILT)

# include $(CLEAR_VARS)
# LOCAL_MODULE := Markup
# LOCAL_MODULE_OWNER := Google
# LOCAL_SRC_FILES := Markup.apk
# LOCAL_CERTIFICATE := shared
# LOCAL_MODULE_TAGS := optional
# LOCAL_MODULE_CLASS := APPS
# LOCAL_MODULE_SUFFIX := .apk
# LOCAL_PRIVILEGED_MODULE := true
# LOCAL_DEX_PREOPT := false
# include $(BUILD_PREBUILT)


